---  # YAML SYNTAX
- name: "Play1 - Install and Configure Apache on webservers inventory"
  hosts: webservers
  tasks:
    - name: "Install Apache"
      yum: name=httpd state=present
    - name: "Copy httpd Configuration file"
      copy: src=/data/httpd.original dest=/etc/httpd/conf/httpd.conf
    - name: "Copy index.html file"
      copy: src=/data/index.html dest=/var/www/html/index.html
      notify:
      - restart apache
    - name: Start and Enable http service
      service: name=httpd state=restarted enabled=yes
     
  handlers:
    - name: restart apache
      service: name=httpd state=restarted
